server.port=8084

spring.application.name=medilabo-back-risk

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=?42AzdK{}sD&16984523Tu
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

spring.security.oauth2.resourceserver.jwt.secret-key-location=classpath:hmac256.key

#jwt.secret=your-base64-encoded-secret-key