server.port=8090
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=?42AzdK{}sD&16984523Tu
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

spring.application.name=spring-CLOUD-GATEWAY

spring.config.import=classpath:medilabo-gateway.yml
spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager=true

server.url=https://localhost:8082

hmac256.key=classpath:hmac256.key
algorithm=HmacSHA256