server.port=8083

spring.application.name=medilabo-back-mongo

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=medilabomongo

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=?42AzdK{}sD&16984523Tu
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

spring.security.oauth2.resourceserver.jwt.secret-key-location=classpath:hmac256.key
# Si vous avez besoin d'authentification pour MongoDB, ajoutez les lignes suivantes :
# spring.data.mongodb.authentication-database=admin
# spring.data.mongodb.username=root
# spring.data.mongodb.password=rootroot


#jwt.secret=your-base64-encoded-secret-key