spring.application.name=medilabo-gui
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=?42AzdK{}sD&16984523Tu
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2

trust.store=classpath:keystore/keystore.p12
trust.store.password=?42AzdK{}sD&16984523Tu

gateway.url=https://localhost:8090

hmac256.key=classpath:hmac256.key
algorithm=HmacSHA256

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration